// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NumberSequenceGameController from "./number_sequence_game_controller"
application.register("number-sequence-game", NumberSequenceGameController)

import RandomNumberGameController from "./random_number_game_controller"
application.register("random-number-game", RandomNumberGameController)

import SpotPurchaseController from "./spot_purchase_controller"
application.register("spot-purchase", SpotPurchaseController)
